export const HOME_SCENE_CAMERA_FOV_DEG = 60;
export const HOME_SCENE_CAMERA_Z = 300;
export const HOME_SCENE_BASE_RADIUS = 120;
export const HOME_SCENE_PARTICLE_RADIUS = HOME_SCENE_BASE_RADIUS * 1.1;
